### ISSUE TITLE
Push rights for cengique

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/com.grangerhub.Tremulous#19]
Please, add push rights to this repository to a new co-maintainer: @cengique

We lost @dGr8LookinSparky to cancer last year (https://github.com/GrangerHub/tremulous/pull/125#issuecomment-1548297377). :-(

/cc @barthalion @nedrichards

**Comment by AsciiWolf** [comment]
@barthalion @nedrichards Ping.

**Comment by cengique** [comment]
Thank you, just accepted it!
