### ISSUE TITLE
Rename this Flatpak

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/com.grangerhub.Tremulous#28]
As mentioned [here](https://github.com/flathub/io.github.grangerhub.Tremulous/issues/3), the old domain has been lost. The Flatpak should be renamed to `org.grangerhub.Tremulous`.

**Comment by cengique** [comment]
Let's hold on before I can confirm that I can access the domain as the community is not as active as before.

**Comment by AsciiWolf** [comment]
Is it possible to get back access to the old `.com` domain? If not, the Flatpak will sadly have to be renamed - not (only) because of the verification, but because of Flathub rules.

**Comment by cengique** [comment]
> Is it possible to get back access to the old `.com` domain? If not, the Flatpak will sadly have to be renamed - not (only) because of the verification, but because of Flathub rules.

Apparently the `.com` domain is on sale for $8k :) I don't think we're getting it back. I definitely understand that we have to rename the flatpak - I saw the references all over the place. The issue is to which domain. If I can't get access to `grangerhub.org` then I'll have to get a new domain.

**Comment by AsciiWolf** [comment]
If the .org domain cannot be accessed by the actual developers, an `io.github.*` namespace can be used instead.

**Comment by cengique** [comment]
> If the .org domain cannot be accessed by the actual developers, an `io.github.*` namespace can be used instead.

I just confirmed that I can get them to put files under the .org domain for the verification process, but I think it may make more sense to just point to Github. Don't you think?

**Comment by AsciiWolf** [comment]
Yep, the github namespace is probably more future proof.

**Comment by AsciiWolf** [comment]
https://github.com/flathub/flathub/pull/5290

**Comment by AsciiWolf** [comment]
Done.
